config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  root :to => 'products#index'

  resource :cart, only: [:show]

  resources :products do
    resources :reviews
  end
  resources :order_items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_items
  before_save :update_total
  before_create :update_status

  def calculate_total
    self.order_items.collect { |item| item.product.price * item.quantity }.sum
  end

  def total_quantity
    self.order_items.collect { |item| item.quantity }.sum
  end

  private

  def update_status
    if self.status == nil?
      self.status = "In progress"
    end
  end

  def update_total
    self.total_price = calculate_total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  validates :quantity, :presence => true
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :presence => true
  validates :price, :presence => true
  has_many :order_items
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
    validates :author, :presence => true
    validates :content, :presence => true
    belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if session[:order_id]
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @order_items = current_order.order_items
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def create
    @order = current_order
    @item = @order.order_items.new(item_params)
    @order.save
      session[:order_id] = @order.id
      flash[:notice] = "Product successfully added to cart!"
        respond_to do |format|
          format.html
          format.js { redirect_to products_path }
        end
  end

  def destroy
   @order = current_order
   @item = @order.order_items.find(params[:id])
   @item.destroy
   @order.save
   redirect_to cart_path
 end

  private

  def item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    if @order.save
    flash[:notice] = "Order successfully added!"
      redirect_to  orders_path
    else
      render :new
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order= Order.find(params[:id])
    if @order.update(order_params)
      flash[:notice] = "Order successfully updated!"
      redirect_to orders_path
    else
      render :edit
    end
  end

  def destroy
    @order = Order.find(params[:id])
    if @order.destroy
      flash[:notice] = "Order successfully removed!"
      redirect_to orders_path
    end
  end

private
  def order_params
    # Use strict parameters, replace placeholder info below with your class' actual attributes
    params.require(:order).permit(:attribute1, :attribute2, :attribute3)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
    flash[:notice] = "Product successfully added!"
      respond_to do |format|
        format.html
        format.js { redirect_to products_path }
      end
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product= Product.find(params[:id])
    if @product.update(product_params)
    flash[:notice] = "Product successfully updated!"
      respond_to do |format|
        format.html
        format.js { redirect_to product_path }
      end
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:notice] = "Product successfully removed!"
      redirect_to products_path
    end
  end

private
  def product_params
    # Use strict parameters, replace placeholder info below with your class' actual attributes
    params.require(:product).permit(:name, :price)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def show
    @review = Review.find(params[:id])
    @product = @review.product
  end

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review successfully added!"
      respond_to do |format|
        format.html
        format.js { redirect_to product_path(@review.product) }
      end
    else
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
    @product = @review.product
  end

  def update
    @review= Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Review successfully updated!"
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy
    @product = Review.find(params[:id]).product
    if Review.find(params[:id]).destroy
      flash[:notice] = "Review successfully removed!"
      redirect_to product_path(@product)
    end
  end

private
  def review_params
    # Use strict parameters, replace placeholder info below with your class' actual attributes
    params.require(:review).permit(:author, :content, :product_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/show.html.erb
<% if @order_items.any? %>
  <% @order_items.each do |item| %>
  <p><%= item.product.name %> <%= link_to "Delete", order_item_path(item), :data => {:confirm => "You sure?", :method => "delete"} %></p>
    <p>Unit Price: <%= number_to_currency item.product.price %></p>
    <p>Quantity: <%= item.quantity %></p>
    <p>Total Price: <%= number_to_currency (item.product.price * item.quantity) %></p><br>
  <% end %>
  <p>Your Total: <%= number_to_currency current_order.total_price %></p>
  <% else %>
  <p>Your shopping cart is empty.</p>
<% end %>

<%= link_to "All Products", products_path %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ship Shop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="jumbotron">
        <h1>Ship Shop</h1>
      </div>
      <header class="navbar navbar-inverse">
        <ul class="nav navbar-nav">
          <li class="home"><%= link_to "Home", products_path %></li>
          <span class="nav-content"><li>Total: <%= number_to_currency current_order.total_price %></li></span>
          <span class="nav-content"><li>(<%= current_order.total_quantity %>)</li></span>
          <li class="nav-cart"><%= link_to "My Cart", cart_path %></li>

        </ul>

      </header>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>

    </div>
  </body>
</html>

app/views/order_items/_form.html.erb
<%= render "layouts/errors", :object => @order_item %>

<%= form_for @order_item do |f| %>
  <%= f.submit %>
<% end %>

app/views/order_items/edit.html.erb
<h1>Edit OrderItem</h1>

<%= render "form" %>

app/views/order_items/index.html.erb
<h1>OrderItems</h1>

<ul>
  <% @order_items.each do |order_item| %>
    <li><%= link_to "Show", order_item_path(order_item) %></li>
  <% end %>
</ul>

<hr>

<%= link_to "New OrderItem", new_order_item_path %>

app/views/order_items/new.html.erb
<h1>New OrderItem</h1>

<%= render "form" %>

app/views/order_items/show.html.erb
<h1>Show OrderItem</h1>

<p><%= link_to "Edit", edit_order_item_path(@order_item) %></p>
<p><%= link_to "Delete", order_item_path(@order_item),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>
<p><%= link_to "Return to order_items", order_items_path %></p>

app/views/orders/_form.html.erb
<%= render "layouts/errors", :object => @order %>

<%= form_for @order do |f| %>
  <%= f.submit %>
<% end %>

app/views/orders/edit.html.erb
<h1>Edit Order</h1>

<%= render "form" %>

app/views/orders/index.html.erb
<h1>Orders</h1>

<ul>
  <% @orders.each do |order| %>
    <li><%= link_to "Show", order_path(order) %></li>
  <% end %>
</ul>

<hr>

<%= link_to "New Order", new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render "form" %>

app/views/orders/show.html.erb
<h1>Show Order</h1>

<p><%= link_to "Edit", edit_order_path(@order) %></p>
<p><%= link_to "Delete", order_path(@order),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>
<p><%= link_to "Return to orders", orders_path %></p>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product, remote: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.submit %>
<% end %>

app/views/products/create.js.erb
$('form').remove();
$('#product_form').show();

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form" %>

app/views/products/edit.js.erb
$('#edit_product_link').hide().after('<%= j render("form") %>')

app/views/products/index.html.erb
<%= link_to "New Product", new_product_path, id:"product_form", remote: true %>
<hr>
<div class="container">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-4">
        <div class="panel panel-transparent">
          <div class="panel-heading"><%= link_to product.name, product_path(product) %>
            <span class="price"><%= number_to_currency product.price %></span>
          </div>
          <div class="panel-body">
            <%= form_for @order_item, remote: true do |f| %>
            <%= f.hidden_field :product_id, value: product.id %>
            <span class="body">
              <%= f.label :quantity %>
              <%= f.select :quantity, options_for_select([
                [ '1', '1'],
                [ '2', '2'],
                [ '3', '3'],
                [ '4', '4'],
                [ '5', '5']
                ]), {} %>
              </span><br><br>
              <span class="cart"><%= f.submit "Add to cart" %></span>
            <% end %>
          </div>
        </div>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form" %>

app/views/products/new.js.erb
$('#product_form').hide().after('<%= j render("form") %>')

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h4>Price: $<%= @product.price %></h4>

<h5><%= link_to "Leave a review", new_product_review_path(@product), id: "new_review_link", remote: true %></h5>
<ul>
  <% @product.reviews.each do |review| %>
  <li><%= review.content %></li>
  <% end %>
</ul>

<p><%= link_to "Edit", edit_product_path(@product), id: "edit_product_link", remote: true %></p>
<p><%= link_to "Delete", product_path(@product),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>
<p><%= link_to "Return to products", products_path %></p>

app/views/products/update.js.erb
$('form').remove();
$('#edit_product_link').show();

app/views/reviews/_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review], remote: true do |f| %>
<%= f.label :author %>
<%= f.text_field :author %>
<%= f.label :content %>
<%= f.text_field :content %>
<%= f.hidden_field(:product_id, :value => @product.id) %>
  <%= f.submit %>
<% end %>

app/views/reviews/create.js.erb
$('form').remove();
$('#new_review_link').show();

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render "form" %>

app/views/reviews/index.html.erb
<h1>Reviews</h1>

<ul>
  <% @reviews.each do |review| %>
    <li><%= link_to "Show", review_path(review) %></li>
  <% end %>
</ul>

<hr>

<%= link_to "New Review", new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render "form" %>

app/views/reviews/new.js.erb
$('#new_review_link').hide().after('<%= j render("form") %>')

app/views/reviews/show.html.erb
<h1>Show Review</h1>

<p><%= link_to "Edit", edit_review_path(@review) %></p>
<p><%= link_to "Delete", review_path(@review),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>
<p><%= link_to "Return to reviews", reviews_path %></p>